networks:
  app:
    driver: bridge

volumes:
  sqlvolume:
  seqdata:

services:
  sqlserver:
    container_name: sqlserver-homolog
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Dmm@dmaack4641"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/home/taskmanagement/docker/ mssql:/var/opt/mssql/data
    networks:
      - app

  container-taskmanagement:
    container_name: container-taskmanagement
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    depends_on:
      - sqlserver
    networks:
      - app
